local function apply_overrides()
	local additionalnodes = {
		["beacon:black"] = "channel",
		["beacon:blue"] = "channel",
		["beacon:cyan"] = "channel",
		["beacon:green"] = "channel",
		["beacon:magenta"] = "channel",
		["beacon:orange"] = "channel",
		["beacon:red"] = "channel",
		["beacon:violet"] = "channel",
		["beacon:white"] = "channel",
		["beacon:yellow"] = "channel",
		["digiline_global_memory:controller"] = "channel",
		["digiline_routing:filter"] = "channel",
		["digilines:chest"] = "channel",
		["digilines:lcd"] = "channel",
		["digilines:lightsensor"] = "channel",
		["digilines:rtc"] = "channel",
		["digiterms:beige_keyboard"] = "channel",
		["digiterms:black_keyboard"] = "channel",
		["digiterms:cathodic_beige_monitor"] = "channel",
		["digiterms:cathodic_black_monitor"] = "channel",
		["digiterms:cathodic_white_monitor"] = "channel",
		["digiterms:lcd_monitor"] = "channel",
		["digiterms:scifi_glassscreen"] = "channel",
		["digiterms:scifi_keysmonitor"] = "channel",
		["digiterms:scifi_tallscreen"] = "channel",
		["digiterms:scifi_widescreen"] = "channel",
		["digiterms:white_keyboard"] = "channel",
		["drawers:controller"] = "digilineChannel",
		["jumpdrive:engine"] = "channel",
		["jumpdrive:fleet_controller"] = "channel",
		["monitoring_digilines:metric_controller"] = "channel",
		["pipeworks:autocrafter"] = "channel",
		["pipeworks:digiline_detector_tube_1"] = "channel",
		["pipeworks:digiline_detector_tube_2"] = "channel",
		["pipeworks:digiline_detector_tube_3"] = "channel",
		["pipeworks:digiline_detector_tube_4"] = "channel",
		["pipeworks:digiline_detector_tube_5"] = "channel",
		["pipeworks:digiline_detector_tube_6"] = "channel",
		["pipeworks:digiline_detector_tube_7"] = "channel",
		["pipeworks:digiline_detector_tube_8"] = "channel",
		["pipeworks:digiline_detector_tube_9"] = "channel",
		["pipeworks:digiline_detector_tube_10"] = "channel",
		["pipeworks:digiline_filter"] = "channel",
		["technic:forcefield_emitter_off"] = "channel",
		["technic:forcefield_emitter_on"] = "channel",
		["technic:hv_battery_box0"] = "channel",
		["technic:hv_battery_box1"] = "channel",
		["technic:hv_battery_box2"] = "channel",
		["technic:hv_battery_box3"] = "channel",
		["technic:hv_battery_box4"] = "channel",
		["technic:hv_battery_box5"] = "channel",
		["technic:hv_battery_box6"] = "channel",
		["technic:hv_battery_box7"] = "channel",
		["technic:hv_battery_box8"] = "channel",
		["technic:hv_nuclear_reactor_core"] = "remote_channel",
		["technic:hv_nuclear_reactor_core_active"] = "remote_channel",
		["technic:lv_battery_box0"] = "channel",
		["technic:lv_battery_box1"] = "channel",
		["technic:lv_battery_box2"] = "channel",
		["technic:lv_battery_box3"] = "channel",
		["technic:lv_battery_box4"] = "channel",
		["technic:lv_battery_box5"] = "channel",
		["technic:lv_battery_box6"] = "channel",
		["technic:lv_battery_box7"] = "channel",
		["technic:lv_battery_box8"] = "channel",
		["technic:mv_battery_box0"] = "channel",
		["technic:mv_battery_box1"] = "channel",
		["technic:mv_battery_box2"] = "channel",
		["technic:mv_battery_box3"] = "channel",
		["technic:mv_battery_box4"] = "channel",
		["technic:mv_battery_box5"] = "channel",
		["technic:mv_battery_box6"] = "channel",
		["technic:mv_battery_box7"] = "channel",
		["technic:mv_battery_box8"] = "channel",
		["technic:quarry"] = "channel",
		["textline:lcd"] = "channel",
	}

	for name,field in pairs(additionalnodes) do
		if minetest.registered_nodes[name] and not minetest.registered_nodes[name]._digistuff_channelcopier_fieldname then
			minetest.override_item(name,{_digistuff_channelcopier_fieldname = field})
		end
	end
end

-- TODO: call apply_overrides() in a delayed callback after all mods have been loaded
