local MP = minetest.get_modpath("pandorabox_custom")

dofile(MP.."/onplace_restriction.lua")
dofile(MP.."/loot.lua")
dofile(MP.."/privs.lua")
dofile(MP.."/death.lua")
dofile(MP.."/travelnet.lua")
dofile(MP.."/skybox.lua")
dofile(MP.."/fly.lua")
dofile(MP.."/stats.lua")
dofile(MP.."/join.lua")
dofile(MP.."/crafts.lua")
dofile(MP.."/ylimit.lua")
dofile(MP.."/grinder.lua")
dofile(MP.."/cnc.lua")
dofile(MP.."/mvps_stopper.lua")
--dofile(MP.."/drawers.lua")
